spring:
  application:
    name: fo

  profiles:
    active: local # 기본 프로파일 활성화

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  threads:
    virtual:
      enabled: true

  # SMTP(Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6380
      password:

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# JWT 만료 시간
jwt:
  access-token-expiration: 3600000 # 1시간
  refresh-token-expiration: 1209600000 # 14일

server:
  port: 8081
 
# 이메일 인증 커스텀 설정
email:
  verification:
    code-length: 6 # 인증 코드 자리수
    expiration-minutes: 5 # 만료 시간(분)
    subject: "[Bureureung] 이메일 인증 코드 안내"